# Generated by Django 3.2.25 on 2024-05-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-12-26'),
            preserve_default=False,
        ),
    ]
